// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect():Promise<void>;

export function Disconnect():Promise<void>;

export function Resize(arg1:number,arg2:number):Promise<void>;

export function Send(arg1:string):Promise<void>;
