// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect() {
  return window['go']['terminal']['SshTerminal']['Connect']();
}

export function Disconnect() {
  return window['go']['terminal']['SshTerminal']['Disconnect']();
}

export function Resize(arg1, arg2) {
  return window['go']['terminal']['SshTerminal']['Resize'](arg1, arg2);
}

export function Send(arg1) {
  return window['go']['terminal']['SshTerminal']['Send'](arg1);
}

export function Startup(arg1) {
  return window['go']['terminal']['SshTerminal']['Startup'](arg1);
}
