// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {internal} from '../models';

export function GetAllThemes():Promise<Array<string>>;

export function GetCustomTheme(arg1:string):Promise<internal.Theme>;

export function GetDarkTheme():Promise<internal.Theme>;

export function GetLightTheme():Promise<internal.Theme>;
