// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllThemes() {
  return window['go']['main']['Theme']['GetAllThemes']();
}

export function GetCustomTheme(arg1) {
  return window['go']['main']['Theme']['GetCustomTheme'](arg1);
}

export function GetDarkTheme() {
  return window['go']['main']['Theme']['GetDarkTheme']();
}

export function GetLightTheme() {
  return window['go']['main']['Theme']['GetLightTheme']();
}
