// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAllThemes():Promise<Array<string>>;

export function GetCustomTheme(arg1:string):Promise<main.Theme>;

export function GetDarkTheme():Promise<main.Theme>;

export function GetLightTheme():Promise<main.Theme>;
